openapi: 3.0.0
info:
  title: Frontent
  description: Frontend services.
  version: 1.0.0

servers:
- url: http://localhost:{port}/frontend/rest
  description: Local development.
  variables:
    port:
      default: "9501"
      description: Server HTTP port.
paths:
  /systemproperties:
    get:
      operationId: getSystemProperties
      responses:
        200:
          description: The current system properties.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
  /tolerant/retry:
    get:
      operationId: tolerantRetry
      responses:
        200:
          description: Ok.
  /tolerant/timeout:
    get:
      operationId: tolerantTimeout
      parameters:
      - name: delay
        in: query
        description: In milliseconds.
        schema:
          type: integer
      responses:
        200:
          description: Ok.
  /tolerant/circuitbreaker:
    get:
      operationId: tolerantCircuitBreaker
      parameters:
      - name: fail
        in: query
        description: true or false
        schema:
          type: boolean
      responses:
        200:
          description: Ok.
  /tolerant/withoutbulkhead:
    get:
      operationId: withoutBulkhead
      responses:
        200:
          description: Ok.
  /tolerant/withbulkhead:
    get:
      operationId: withBulkhead
      responses:
        200:
          description: Ok.
